name: scan

on:
  workflow_dispatch:
#  schedule:
#    - cron: "00 00 */1 * *"

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Run Snyk to check Docker images for vulnerabilities (alpine:3.13)
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: ${{ secrets.DOCKER_USER }}/alpine:3.13

#    - name: Upload result to GitHub Code Scanning
#      uses: github/codeql-action/upload-sarif@v1
#      with:
#        sarif_file: snyk.sarif
